group:
  repos: |
    Qbox-project/mhacking
    Qbox-project/npwd_qbx_garages
    Qbox-project/npwd_qbx_mail
    Qbox-project/PolyZone
    Qbox-project/qbx_adminmenu
    Qbox-project/qbx_ambulancejob
    Qbox-project/qbx_apartments
    Qbox-project/qbx_bankrobbery
    Qbox-project/qbx_binoculars
    Qbox-project/qbx_busjob
    Qbox-project/qbx_carwash
    Qbox-project/qbx_cityhall
    Qbox-project/qbx_core
    Qbox-project/qbx_customs
    Qbox-project/qbx_divegear
    Qbox-project/qbx_diving
    Qbox-project/qbx_drugs
    Qbox-project/qbx_fireworks
    Qbox-project/qbx_garages
    Qbox-project/qbx_garbagejob
    Qbox-project/qbx_houserobbery
    Qbox-project/qbx_houses
    Qbox-project/qbx_hud
    Qbox-project/qbx_idcard
    Qbox-project/qbx_interior
    Qbox-project/qbx_jewelery
    Qbox-project/qbx_lapraces
    Qbox-project/qbx_loading
    Qbox-project/qbx_lockpick
    Qbox-project/qbx_management
    Qbox-project/qbx_mechanicjob
    Qbox-project/qbx_medical
    Qbox-project/qbx_newsjob
    Qbox-project/qbx_npwd
    Qbox-project/qbx_pawnshop
    Qbox-project/qbx_policejob
    Qbox-project/qbx_prison
    Qbox-project/qbx_properties
    Qbox-project/qbx_radialmenu
    Qbox-project/qbx_radio
    Qbox-project/qbx_recyclejob
    Qbox-project/qbx_scoreboard
    Qbox-project/qbx_scrapyard
    Qbox-project/qbx_seatbelt
    Qbox-project/qbx_smallresources
    Qbox-project/qbx_spawn
    Qbox-project/qbx_storerobbery
    Qbox-project/qbx_streetraces
    Qbox-project/qbx_taxijob
    Qbox-project/qbx_towjob
    Qbox-project/qbx_truckerjob
    Qbox-project/qbx_truckrobbery
    Qbox-project/qbx_vehiclefailure
    Qbox-project/qbx_vehiclekeys
    Qbox-project/qbx_vehicles
    Qbox-project/qbx_vehiclesales
    Qbox-project/qbx_vehicleshop
    Qbox-project/qbx_vineyard
    Qbox-project/qbx_weed
    Qbox-project/safecracker
    Qbox-project/txAdminRecipe
  files:
  - source: repo-template/
    dest: ./