group:
  repos: |
    Qbox-project/qbx-radialmenu
    Qbox-project/qbx-policejob
    Qbox-project/qbx-vehiclekeys
    Qbox-project/qbx-core
    Qbox-project/qbx-adminmenu
    Qbox-project/qbx-multicharacter
    Qbox-project/qbx-ambulancejob
    Qbox-project/qbx-medical
    Qbox-project/qbx-cityhall
    Qbox-project/qbx-vehiclefailure
    Qbox-project/qbx-truckerjob
    Qbox-project/qbx-garages
    Qbox-project/qbx-hud
    Qbox-project/qbx-weathersync
    Qbox-project/qbx-towjob
    Qbox-project/qbx-storerobbery
    Qbox-project/qbx-properties
    Qbox-project/qbx-skillbar
    Qbox-project/qbx-smallresources
    Qbox-project/qbx-phone
    Qbox-project/qbx-bankrobbery
    Qbox-project/qbx-traphouse
    Qbox-project/qbx-scrapyard
    Qbox-project/qbx-jewelery
    Qbox-project/qbx-management
    Qbox-project/qbx-loading
    Qbox-project/qbx-vehicleshop
    Qbox-project/qbx-mechanicjob
    Qbox-project/interact-sound
    Qbox-project/qbx-recyclejob
    Qbox-project/qbx-garbagejob
    Qbox-project/qbx-apartments
    Qbox-project/qbx-spawn
    Qbox-project/qbx-weed
    Qbox-project/qbx-vineyard
    Qbox-project/qbx-vehiclesales
    Qbox-project/qbx-tunerchip
    Qbox-project/qbx-truckrobbery
    Qbox-project/qbx-taxijob
    Qbox-project/qbx-streetraces
    Qbox-project/qbx-scoreboard
    Qbox-project/qbx-prison
    Qbox-project/qbx-pawnshop
    Qbox-project/qbx-newsjob
    Qbox-project/qbx-lockpick
    Qbox-project/qbx-lapraces
    Qbox-project/qbx-interior
    Qbox-project/qbx-houses
    Qbox-project/qbx-houserobbery
    Qbox-project/qbx-fitbit
    Qbox-project/qbx-drugs
    Qbox-project/qbx-diving
    Qbox-project/qbx-crypto
    Qbox-project/qbx-commandbinding
    Qbox-project/qbx-busjob
    Qbox-project/qbx-hotdogjob
    Qbox-project/qbx-npwd
    Qbox-project/qbx-weapons
    Qbox-project/qbx-atms
    Qbox-project/qbx-radio
    Qbox-project/qbx-customs
    Qbox-project/qbx-printer
    Qbox-project/qbx-anticheat
    Qbox-project/safecracker
    Qbox-project/PolyZone
    Qbox-project/connectqueue
    Qbox-project/mhacking
  files:
  - source: repo-template/.github/
    dest: .github/
